version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

  chempath:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j:7687
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs: